export const ActionType = {
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    LOADING: 'LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOAD_USER: 'LOAD_USER',
    LOAD_USER_FAIL: 'LOAD_USER_FAIL:',
    LOGOUT: 'LOGOUT',
    LOAD_HOTELS: 'LOAD_HOTELS',
    LOAD_HOTELS_FAIL: 'LOAD_HOTELS_FAIL',
    LOAD_HOTEL_ID: 'LOAD_HOTEL_ID',
    LOAD_HOTEL_ID_FAIL: 'LOAD_HOTEL_ID'
}